config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  get 'flights/index'
  resources :bookings, only: [:new, :show, :create]
end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :arriving_flights, class_name: "Flight", foreign_key: "to_airport_id"
  has_many :departing_flights, class_name: "Flight", foreign_key: "from_airport_id"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flight
  has_many :passengers, through: :passenger_bookings
  has_many :passenger_bookings
  
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :from_airport, class_name: "Airport"
  belongs_to :to_airport, class_name: "Airport"
  has_many :bookings
  has_many :passengers, through: :passenger_bookings

  def self.search(params)
    if params[:search] 
      date = params[:date].to_date
      Flight.where(from_airport_id: params[:from], to_airport_id: params[:to], 
                   start_time: date.beginning_of_day..date.end_of_day)
                  .order(start_time:  :asc)
    else
      Flight.none
    end
  end

  def self.flying_dates
    pluck(:start_time).sort.map{ |d| [d.strftime("%a, %b %d,%Y"), d.to_date] }.uniq
  end

  def flight_date
     date = self.start_time.strftime("%b %d %Y")
  end

  def flight_time
    time = self.start_time.strftime("%H:%M %Z")
  end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  has_many :bookings, through: :passenger_bookings
  has_many :passenger_bookings
  has_many :flights, through: :bookings

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX }
end

app/models/passenger_booking.rb
class PassengerBooking < ActiveRecord::Base
  belongs_to :booking
  belongs_to :passenger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])
    @booking = Booking.new
    @passenger_count = params[:passengers].to_i
    @passenger_count.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer.thank_you(passenger).deliver!
      end
      flash[:success] = "Your booking has been saved!"
      redirect_to @booking
    else
      @flight = Flight.find(params[:flight_id])
      render :new
    end
  end


  def show
    @booking = Booking.find(params[:id])
  end

  private
    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  
  def index
    @airports = Airport.all.map {|a| [a.code, a.id]}
    @passengers = [[1,1],[2,2],[3,3],[4,4]]
    @dates = Flight.flying_dates
    @flights = Flight.search(params)
    @all_flights = Flight.all
    respond_to do |format|
      format.html
      format.json { render :json => @all_flights }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div id="flight-info">
      <h1>Flight details</h1>
      <table>
        <tr>
          <th>Flight #</th>
          <th>From</th>
          <th>To</th>
          <th>Date</th>
          <th>Time</th>
          <th>Duration</th>
        </tr>
        <tr>
          <td><%= @flight.id %></td>
          <td><%= @flight.from_airport.code %></td>
          <td><%= @flight.to_airport.code %></td>
          <td><%= @flight.flight_date %></td>
          <td><%= @flight.flight_time.in_time_zone("EST") %></td>
          <td><%= distance_of_time_in_words(@flight.duration) %></td>
        </tr>
      </table>
    </div>
    <div class="booking-form">
      <h2>Enter passenger details</h2>
      <% passenger_num = 1 %>
      <%= form_for @booking do |flight| %>
          <%= render 'shared/error_messages', object: flight.object %>
          <%= flight.fields_for :passengers do |p| %>
            <h3>Passenger <%= passenger_num %></h3>
            <% passenger_num += 1 %>
            <div class="form-group">
              <%= p.label :name, "Name:", class: "control-label" %>
              <%= p.text_field :name, class: "form-control"%>
            </div>
            <div class="form-group">
              <%= p.label :email, "Email:", class: "control-label" %>
              <%= p.email_field :email, class: "form-control"%>
            </div>
          <% end %>
        <%= flight.hidden_field(:flight_id, value: params[:flight_id]) %>
        <%= flight.submit "Book Flight" %>
      <% end %>   
    </div>
  </div>
</div>  

app/views/bookings/show.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div id="flight-info">
      <h1>Flight details</h1>
      <table>
        <tr>
          <th>Flight #</th>
          <th>From</th>
          <th>To</th>
          <th>Date</th>
          <th>Time</th>
          <th>Duration</th>
        </tr>
        <tr>
          <td><%= @booking.flight.id %></td>
          <td><%= @booking.flight.from_airport.code %></td>
          <td><%= @booking.flight.to_airport.code %></td>
          <td><%= @booking.flight.flight_date %></td>
          <td><%= @booking.flight.flight_time.in_time_zone("EST") %></td>
          <td><%= distance_of_time_in_words(@booking.flight.duration) %></td>
        </tr>
      </table>
    </div>
    <div class="booking-details">
      <h2>Passenger details</h2>
      <% passenger_num = 1 %>
      <% @booking.passengers.each do |passenger| %>
        <h3>Passenger <%= passenger_num %></h3>
        <% passenger_num += 1 %>
        Name: <%= passenger.name %><br />
        Email: <%= passenger.email %><br />
      <% end %>   
    </div>
  </div>
</div>  

app/views/flights/index.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div class="page-header">
      <h1>Search for flights</h1>
    </div>

    <%= form_tag root_path, method: "get", class: "form-inline" do %>
      <%= hidden_field_tag :search %>
      <div class="form-group">
        <%= label_tag :from %> <%= select_tag :from, options_for_select(@airports, params[:from]), class: "form-control" %>         
      </div>
      <div class="form-group">
        <%= label_tag :to %> <%= select_tag :to, options_for_select(@airports, params[:to]), class: "form-control" %> 
      </div>
      <div class="form-group">
        <%= label_tag :passengers, "Number of passengers" %> <%= select_tag :passengers, options_for_select(@passengers, params[:passengers]), class: "form-control" %> 
      </div>
      <div class="form-group">
        <%= label_tag :date %> <%= select_tag :date, options_for_select(@dates, params[:date]), class: "form-control" %> 
      </div>
      <%= submit_tag "Search", class: "btn btn-default" %>
    <% end %>
  </div>
  <div class="col-md-10 col-md-offset-1">
 
    <% unless @flights.empty? %>
      <div id="search-results">
        <h3>Choose a flight</h3>
        <%= form_tag(new_booking_path, method: "get") do %>
          <table>
            <tr>
              <th></th>
              <th>Flight #</th>
              <th>From Airport</th>
              <th>To Airpoit</th>
              <th>Date</th>
              <th>Departure Time</th>
              <th>Duration</th>
            </tr> 
            <!-- Search results --> 
            <% @flights.each do |flight| %>
              <tr>
                <td><%= radio_button_tag(:flight_id, flight.id) %></td>
                <td><%= flight.id %></td>
                <td><%= flight.from_airport.code %></td>
                <td><%= flight.to_airport.code %></td>
                <td><%= flight.flight_date %></td>
                <td><%= flight.flight_time.in_time_zone("EST") %></td>
                <td><%= distance_of_time_in_words(flight.duration) %></td>
              </tr>
            <% end %> 
          </table>
          <%= hidden_field_tag(:passengers, params[:passengers]) %>
          <%= submit_tag "Continue" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinFlightBooker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div col>
<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>